language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - io-refactor
    - master
    - refactor/performance-refactor
    - milestone/mvp

addons:
  apt:
    packages:
      - gdal-bin
      - libproj-dev
      - libhdf5-serial-dev
      - libpng12-dev
      - libgdal-dev
      - libatlas-dev
      - libatlas-base-dev
      - gfortran
      - oracle-java8-set-default

install:
  - pushd geopyspark-backend &&
    ./sbt "project geotrellis-backend" assembly &&
    cp geotrellis/target/scala-2.11/geotrellis-backend-assembly-0.2.0.jar ../geopyspark/jars &&
    popd
  - if [ ! -f archives/spark-2.1.1-bin-hadoop2.7.tgz ]; then
    pushd archives;
    wget http://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.7.tgz;
    popd;
    fi
  - tar -xvf archives/spark-2.1.1-bin-hadoop2.7.tgz
  - pip3 install -r requirements.txt
  - pip3 install pyproj
  - pip3 install pylint
  - pip3 install jupyter
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then
    pip3 install pathlib;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION != "3.3" ]]; then
    pip3 install matplotlib==2.0.0;
    fi
  - pip3 install colortools==0.1.2
  - pip3 install .

cache:
  directories:
  - ./archives
  - $HOME/.ivy2
  - $HOME/.cache/pip

script:
  - export SPARK_HOME=/home/travis/build/locationtech-labs/geopyspark/spark-2.1.1-bin-hadoop2.7/
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - ./test_script.sh
  - pylint geopyspark
